// Code generated by MockGen. DO NOT EDIT.
// Source: avatar-service/internal/services/avatar (interfaces: EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_event_publisher.go -package=mocks avatar-service/internal/services/avatar EventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "avatar-service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishAvatarDeleted mocks base method.
func (m *MockEventPublisher) PublishAvatarDeleted(ctx context.Context, event domain.AvatarDeletedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAvatarDeleted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAvatarDeleted indicates an expected call of PublishAvatarDeleted.
func (mr *MockEventPublisherMockRecorder) PublishAvatarDeleted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAvatarDeleted", reflect.TypeOf((*MockEventPublisher)(nil).PublishAvatarDeleted), ctx, event)
}

// PublishAvatarUploaded mocks base method.
func (m *MockEventPublisher) PublishAvatarUploaded(ctx context.Context, event domain.AvatarUploadedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAvatarUploaded", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAvatarUploaded indicates an expected call of PublishAvatarUploaded.
func (mr *MockEventPublisherMockRecorder) PublishAvatarUploaded(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAvatarUploaded", reflect.TypeOf((*MockEventPublisher)(nil).PublishAvatarUploaded), ctx, event)
}
