// Code generated by MockGen. DO NOT EDIT.
// Source: avatar-service/internal/services/avatar (interfaces: AvatarRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_avatar_repository.go -package=mocks avatar-service/internal/services/avatar AvatarRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "avatar-service/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAvatarRepository) Create(ctx context.Context, avatar *domain.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAvatarRepositoryMockRecorder) Create(ctx, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAvatarRepository)(nil).Create), ctx, avatar)
}

// GetByID mocks base method.
func (m *MockAvatarRepository) GetByID(ctx context.Context, id string) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAvatarRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAvatarRepository)(nil).GetByID), ctx, id)
}

// GetUserAvatar mocks base method.
func (m *MockAvatarRepository) GetUserAvatar(ctx context.Context, userID string) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAvatar", ctx, userID)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAvatar indicates an expected call of GetUserAvatar.
func (mr *MockAvatarRepositoryMockRecorder) GetUserAvatar(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).GetUserAvatar), ctx, userID)
}

// ListByUserID mocks base method.
func (m *MockAvatarRepository) ListByUserID(ctx context.Context, userID string) ([]*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAvatarRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).ListByUserID), ctx, userID)
}

// SoftDelete mocks base method.
func (m *MockAvatarRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockAvatarRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockAvatarRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockAvatarRepository) Update(ctx context.Context, avatar *domain.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAvatarRepositoryMockRecorder) Update(ctx, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAvatarRepository)(nil).Update), ctx, avatar)
}
